- package.json
- yarn.lock
Upgrade `react-scripts` to latest
> Upgrade react-scripts and i18next

- .travis.yml
- src/index.tsx
CD is missing since we have nowhere to deploy to at the moment
> KK-31 | Add initial Travis configuration

- .vscode/launch.json
- README.md
- package.json
VS Code config for normal & test debugging
package.json script for debugging without VS Code
Readme.md update
https://helsinkisolutionoffice.atlassian.net/browse/KK-35
> KK-35 | Add debug configuration for VSCode and instructions for debugging

- package.json
- src/common/test/testUtils.tsx
- src/domain/app/BrowserApp.tsx
- src/domain/app/__tests__/BrowserApp.test.tsx
- src/domain/app/state/AppStore.tsx
- src/domain/auth/state/authSelectors.tsx
- yarn.lock
Persist registration data only, cause authentication data is persisted already by redux-oidc itself
> KK-56 | Add redux-persist to persist form information

- src/domain/api/generatedTypes/profileQuery.ts
- src/domain/profile/Profile.tsx
- src/domain/profile/queries/ProfileQuery.ts
- src/domain/profile/state/ProfileReducers.tsx
This removes a warning about missing keys in browser developer console
We need those keys for crud operations too
> KK-123 | Add key to child list

- src/common/components/form/__tests__/validationUtils.tests.tsx
- src/common/components/form/validationUtils.tsx
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/registration/form/partial/ChildFormField.tsx
I chose to use regex because the leading zeroes of Finnish postal codes makes any other type of check really complicated.
> KK-124 | Validation for postal code

- src/domain/api/generatedTypes/globalTypes.ts
- src/domain/api/generatedTypes/profileQuery.ts
- src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
- src/domain/profile/queries/ProfileQuery.ts
- src/domain/profile/state/ProfileReducers.tsx
- src/domain/registration/form/RegistrationForm.tsx
- src/domain/registration/form/partial/ChildFormField.tsx
Bonus: Get the language of the guardian from the API
> Add postalCode and relationship to submit child mutation

- src/common/components/modal/Modal.tsx
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/child/modal/ChildFormModal.tsx
- src/domain/child/modal/childFormModal.module.scss
- src/domain/registration/form/partial/ChildFormField.tsx
- src/domain/registration/modal/AddNewChildFormModal.tsx
- Add postalCode validation for modal
- Turn off click overlay to hide modal
> KK-123 | Add not eligible warning for child modal

- src/domain/registration/form/RegistrationForm.tsx
Before this fix you will get a validation error for the language field every time you try to submit the registration form. You have to change preferred language in the form to some other language and back again to be able to submit.
> KK-152 | Fix language validation error on registration form

- src/domain/registration/form/RegistrationForm.tsx
- src/domain/registration/state/RegistrationSelectors.ts
- src/domain/registration/welcome/Welcome.tsx
- src/domain/registration/welcome/__tests__/Welcome.test.tsx
- src/domain/registration/welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
Bonus: Remove unused selector from RegistrationForm page.
> Users should not see registration form any more after submitting it

- src/domain/api/generatedTypes/addNewChild.ts
- src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
- src/domain/app/header/userDropdown/UserDropdown.tsx
- src/domain/child/modal/ChildFormModal.tsx
- src/domain/profile/CheckHasProfile.tsx
- src/domain/profile/Profile.tsx
- src/domain/profile/ProfileUtils.ts
- src/domain/profile/__tests__/CheckHasProfile.test.tsx
- src/domain/profile/__tests__/__snapshots__/CheckHasProfile.test.tsx.snap
- src/domain/registration/form/RegistrationForm.tsx
- src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
- src/domain/registration/welcome/Welcome.tsx
1. If a user already has a profile, and still tries to use front page form, send them to their existing profile
2. The Profile page often gives an error even though everything is fine. Don't give an error.
> KK-165 | Prevent bugs with signup and logging in

- package.json
- src/domain/app/state/AppReducers.ts
- src/domain/app/state/AppStore.ts
- src/domain/app/types/AppTypes.ts
- src/domain/auth/authenticate.ts
- src/domain/auth/state/BackendAuthenticationActions.ts
- src/domain/auth/state/BackendAuthenticationReducer.ts
- src/domain/profile/state/ProfileActions.tsx
- src/domain/profile/state/ProfileReducers.tsx
- src/domain/registration/state/RegistrationActions.tsx
- src/domain/registration/state/RegistrationReducers.tsx
- yarn.lock
https://www.npmjs.com/package/redux-starter-kit
Package renamed
> KK-187 | Replace deprecated redux-starter-kit with redux-tooltip

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/auth/state/BackendAuthenticationActions.ts
- src/domain/home/form/partial/BirthdateFormField.tsx
@Zeukkari : You can ignore changes made to json files, it happened because i sort the Google translation sheet
`validateDate` util return raw string which is not translated
> Fix custom birthdate validation not getting translated

- src/common/components/form/fields/input/NumberInputField.tsx
- src/domain/home/form/partial/BirthdateFormField.tsx
HTML number input doesnt respect `min` and `max` property. 
Manually give custom `maxLength` limit to number input
> KK-188 | use maxLength to limit amount of char in input number

- .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> sudo is no longer required

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
I think this reads a little better.
The original sounds a bit more like a direct Finnish translation.
Shorter is usually better online, people scan rather than reading text.
> Simplify text

- src/common/components/modal/Modal.tsx
- src/common/components/modal/modal.module.scss
- src/domain/child/modal/ChildFormModal.tsx
- src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
- src/domain/profile/children/child/ProfileChildDetail.tsx
- src/domain/profile/children/child/profileChildDetail.module.scss
- src/domain/profile/profile.module.scss
- Remove modal dynamic size
- Tweaks for better mobile layout
> Mobile profile view

- package.json
- public/index.html
- src/domain/app/BrowserApp.tsx
- src/domain/app/header/userDropdown/UserDropdown.tsx
- src/domain/app/layout/PageWrapper.tsx
- src/domain/profile/children/ProfileChildrenList.tsx
- src/domain/profile/modal/EditProfileModal.tsx
- src/domain/registration/notEligible/NotEligible.tsx
- src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
- yarn.lock
I finally found a matomo npm module that seems to work well, it comes with typescript out of the box. 
Any ideas for more things to track?
> KK-215 | Improve analytics

- CHANGELOG.md
- src/assets/styles/variables.scss
- src/common/components/modal/Modal.tsx
- src/common/components/modal/modal.module.scss
- src/domain/child/modal/childFormModal.module.scss
- src/domain/profile/children/ProfileChildrenList.tsx
- src/domain/profile/children/child/profileChildDetail.module.scss
- src/domain/profile/children/profileChildrenList.module.scss
- src/domain/profile/modal/editProfileModal.module.scss
- src/domain/profile/profile.module.scss
* Move add child button below child list
* Profile page edit button aligns as well as possible with name
* Hide back button on child detail page
* Modal has correct button order on small screen and correct size on big screen
> KK-123 | Adjustments for small screens and modal fixes

- CHANGELOG.md
- src/domain/auth/authenticate.ts
This should fix #146 - it does require that Tunnistamo is configured correctly.
> KK-250 | Ensure that login page is in user's chosen language

- src/assets/styles/variables.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/api/client.ts
- src/domain/api/generatedTypes/eventQuery.ts
- src/domain/api/generatedTypes/globalTypes.ts
- src/domain/app/App.tsx
- src/domain/app/header/navbar/navbar.module.scss
- src/domain/event/Event.tsx
- src/domain/event/EventOccurrence.tsx
- src/domain/event/EventOccurrenceList.tsx
- src/domain/event/event.module.scss
- src/domain/event/eventOccurrence.module.scss
- src/domain/event/eventOccurrenceList.module.scss
- src/domain/event/queries/eventQuery.ts
- src/domain/event/route/EventRoute.tsx
To test, go directly to the url of an event (you need to figure out the uuid somehow) like this:
http://localhost:3000/fi/event/RXZlbnROb2RlOjE=
It looks something like this: 
Note that having TODOs in here is OK, we will resolve them in KK-300.
> KK-299 | RFC: Event page version 0.0.1

- src/common/components/card/Card.tsx
- src/common/components/card/__tests__/__snapshots__/Card.test.tsx.snap
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap
This makes the Card component even dumber: It shouldn't know the actions used on it but be told by the calling component.
> KK-327 | Use translations for event list and card actions

- src/assets/icons/svg/calendar.svg
- src/common/components/card/Card.tsx
- src/common/components/card/card.module.scss
- src/domain/api/generatedTypes/childByIdQuery.ts
- src/domain/child/queries/ChildQueries.ts
- src/domain/profile/children/child/profileChildDetail.module.scss
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/events/__tests__/ProfileEventsList.test.tsx
- src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap
- src/domain/profile/events/profileEventsList.module.scss
> KK-328, KK-329, KK-330, KK-331 | Child's events list page fixes

- src/common/components/modal/modal.module.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/api/generatedTypes/childByIdQuery.ts
- src/domain/api/generatedTypes/enrolOccurrenceMutation.ts
- src/domain/api/generatedTypes/globalTypes.ts
- src/domain/api/generatedTypes/occurrenceQuery.ts
- src/domain/api/generatedTypes/unenrolOccurrenceMutation.ts
- src/domain/event/Event.tsx
- src/domain/event/EventIsEnrolled.tsx
- src/domain/event/EventOccurrence.tsx
- src/domain/event/enrol/Enrol.tsx
- src/domain/event/event.module.scss
- src/domain/event/modal/UnenrolModal.tsx
- src/domain/event/mutations/enrolOccurrenceMutation.ts
- src/domain/event/mutations/unenrolOccurrenceMutation.ts
- src/domain/event/partial/OccurrenceInfo.tsx
- src/domain/event/partial/occurrenceInfo.module.scss
- src/domain/event/queries/occurrenceQuery.ts
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/route/ProfileRoute.tsx
I added some TODOs with a reference to Jira-issues, hoping that we won't lose track of them
> KK-282 | Add support for enrolling and cancelling enrolment

- Dockerfile
- src/assets/styles/mixins.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/api/client.ts
- src/domain/api/generatedTypes/eventQuery.ts
- src/domain/event/Event.tsx
- src/domain/event/EventEnrol.tsx
- src/domain/event/EventOccurrence.tsx
- src/domain/event/EventOccurrenceList.tsx
- src/domain/event/__tests__/__snapshots__/EventOccurrenceList.test.tsx.snap
- src/domain/event/enrol/Enrol.tsx
- src/domain/event/eventOccurrence.module.scss
- src/domain/event/modal/UnenrolModal.tsx
- src/domain/event/queries/eventQuery.ts
- src/index.tsx
I went a bit overboard with this PR and started on the occurrence filter. 
With the current implementation the filter dropdown only contains occurrences that match the current selection, so if you filter on for example tomorrow there is no way to switch to another day.
> KK-279, KK-280 | Handle enrolment failed, Add filter by date and time

- src/domain/api/generatedTypes/occurrenceQuery.ts
- src/domain/event/Event.tsx
- src/domain/event/EventIsEnrolled.tsx
- src/domain/event/EventPage.tsx
- src/domain/event/enrol/Enrol.tsx
- src/domain/event/queries/occurrenceQuery.ts
This PR 
- ensures that the image alt text shows up every place where it belongs
- reduces the duplication of code on the event pages
> KK-373 | Refactor event page

- src/common/components/card/card.module.scss
- src/common/components/collapsible/collapsible.module.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/event/EventOccurrenceList.tsx
- src/domain/event/__tests__/__snapshots__/EventOccurrenceList.test.tsx.snap
- src/domain/event/enrol/Enrol.tsx
- src/domain/event/enrol/enrol.module.scss
- src/domain/event/event.module.scss
- src/domain/event/eventOccurrence.module.scss
- src/domain/event/eventOccurrenceList.module.scss
- src/domain/event/partial/InfoItem.tsx
- src/domain/event/partial/OccurrenceInfo.tsx
- src/domain/event/partial/__tests__/InfoItem.test.tsx
- src/domain/event/partial/__tests__/__snapshots__/InfoItem.test.tsx.snap
- src/domain/event/partial/__tests__/__snapshots__/OccurrenceInfo.test.tsx.snap
- src/domain/event/partial/occurrenceInfo.module.scss
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap
- src/domain/profile/events/profileEventsList.module.scss
* Less margin on child info page on desktops
* Make the QR code look more similar to the event image
* Hide participants from child upcoming events info
* Center remaining capacity number on occurrence list screen
* Refactor OccurrenceInfo - less code duplication
* Add option to hide items from OccurrenceInfo
* Show confirm text on confirm screen
* Update translations
> KK-300, KK-394 | Improve event enrolment layouts and structure

- src/common/components/card/Card.tsx
- src/common/components/card/__tests__/__snapshots__/Card.test.tsx.snap
- src/domain/event/enrol/SuccessToast.tsx
- src/domain/event/enrol/__tests__/__snapshots__/SuccessToast.test.tsx.snap
- src/domain/event/enrol/successToast.module.scss
- src/domain/event/partial/__tests__/__snapshots__/InfoItem.test.tsx.snap
Bonus:
* Make all card components clickable
* Ensure that setTimeout is always cleared
> KK-342 | Improve SuccessToast placement and size on all screen sizes

- src/domain/api/generatedTypes/ChildrenQuery.ts
- src/domain/api/generatedTypes/addNewChild.ts
- src/domain/api/generatedTypes/childByIdQuery.ts
- src/domain/api/generatedTypes/profileQuery.ts
- src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
- src/domain/api/generatedTypes/updateChild.ts
- src/domain/child/mutation/ChildMutation.ts
- src/domain/child/queries/ChildQueries.ts
- src/domain/profile/ProfileUtil.ts
- src/domain/profile/children/ProfileChildrenList.tsx
- src/domain/profile/queries/ProfileQuery.ts
- src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
To test this, you need to 
* ensure that you have more than one project in kukkuu backend (add through django)
And either
* edit `SUPPORTED_START_BIRTHDATE` `src/common/time/TimeConstants.ts` to allow 2019 as start year  and add a child born in 2019
* OR edit a child through a mutation to be born in 2019
> KK-424 | Add support for projects to profile children list

- src/domain/app/App.tsx
- src/domain/event/Event.tsx
- src/domain/event/EventEnrol.tsx
- src/domain/event/EventIsEnrolled.tsx
- src/domain/event/EventPage.tsx
- src/domain/event/modal/UnenrolModal.tsx
- src/domain/profile/state/ProfileActions.tsx
According to this discussion there is no real need to use FunctionComponent:
https://github.com/facebook/create-react-app/pull/8177
According to this discussion it is better to use ReactElement type instead of ReactNode:
https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement
> Improve typing for EventPage and avoid FunctionComponent when not needed

- src/domain/api/__tests__/client.test.ts
- src/domain/api/generatedTypes/addNewChild.ts
- src/domain/api/generatedTypes/childByIdQuery.ts
- src/domain/api/generatedTypes/profileQuery.ts
- src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
- src/domain/api/generatedTypes/updateChild.ts
- src/domain/child/mutation/ChildMutation.ts
- src/domain/child/queries/ChildQueries.ts
- src/domain/event/queries/eventQuery.ts
- src/domain/profile/ProfileUtil.ts
- src/domain/profile/children/ProfileChildrenList.tsx
- src/domain/profile/queries/ProfileQuery.ts
- src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
Bonus: Remove query that is not in use
> KK-437 | Show project name for child list

- src/common/components/form/fields/input/inputField.module.scss
- src/domain/home/form/partial/birthdateFormField.module.scss
This improvement should also be project wide, not just for that form
> KK-452 | Ensure that input spinners/arrows are not visible in Firefox too

- yarn.lock
`yarn audit` reported one high security vulnerability in a dependency of a direct dependency
I created this pull request by copying package.json to a temp folder, running yarn, and copying it back. Huh!
> Update dependencies to resolve security issue

- src/domain/api/generatedTypes/GuardiansQuery.ts
- src/domain/api/generatedTypes/globalTypes.ts
- src/domain/api/generatedTypes/profileQuery.ts
- src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
- src/domain/api/generatedTypes/updateMyProfile.ts
- src/domain/registration/form/RegistrationForm.tsx
This is draft because it depends on a backend change
> KK-476 | Make it possible to change the email address while signing up

- src/assets/styles/variables.scss
- src/common/components/alert/alertModal.module.scss
- src/common/components/button/button.module.scss
- src/common/components/dropdown/dropdown.module.scss
- src/common/components/input/input.module.scss
- src/common/components/modal/modal.module.scss
- src/common/components/select/select.module.scss
- src/domain/app/header/navbar/languageBar/languageBar.module.scss
- src/domain/app/header/navbar/smallScreenNav/smallScreenNav.module.scss
- src/domain/app/notFound/notFound.module.scss
- src/domain/event/enrol/successToast.module.scss
- src/domain/event/event.module.scss
- src/domain/event/eventOccurrence.module.scss
- src/domain/home/form/homePreliminaryForm.module.scss
- src/domain/home/hero/hero.module.scss
- src/domain/profile/children/child/profileChild.module.scss
- src/domain/profile/children/child/profileChildDetail.module.scss
- src/domain/profile/children/profileChildrenList.module.scss
- src/domain/profile/events/profileNoEvent.module.scss
- src/domain/profile/profile.module.scss
- src/domain/registration/form/registrationForm.module.scss
- src/domain/registration/welcome/welcome.module.scss
Now that we started using CSS-variables for colors we don't need to import the scss file
> Remove obsolete import

- src/domain/profile/children/ProfileChildrenList.tsx
> Fix TypeScript error:  null is not an object (evaluating ‘t.edges’)

- .github/PULL_REQUEST_TEMPLATE.md
I've added a PR template file.
This file will make it easier for the developer to provide all the relevant information in a consistent format.
No Jira ticket.
This has been tested by using Visual Studio Code's preview. The template has also been dogfooded for this PR description.
This template can be tested only after it has been merged into develop.
> Chore | Add PR template

- CHANGELOG.md
- package.json
- [#302](https://github.com/City-of-Helsinki/kukkuu-ui/pull/302) Error handling for child already enrolled error
- [#305](https://github.com/City-of-Helsinki/kukkuu-ui/pull/305) Logo of Finnish National Gallery to the home page
- [#303](https://github.com/City-of-Helsinki/kukkuu-ui/pull/303) Option to subscribe to places once they become available
- [#312](https://github.com/City-of-Helsinki/kukkuu-ui/pull/312) Languages spoken at home field into the interface
- [#299](https://github.com/City-of-Helsinki/kukkuu-ui/pull/299) Show no other button than log out for logged in unregistered users
- [#301](https://github.com/City-of-Helsinki/kukkuu-ui/pull/301) Update accessibility statement
- [#304](https://github.com/City-of-Helsinki/kukkuu-ui/pull/304) Show events as upcoming events also for a …
> [develop] Release 1.5.0

- src/domain/child/form/ChildForm.tsx
Remove rogue test left in by accident.
[PR comment](https://github.com/City-of-Helsinki/kukkuu-ui/pull/325#pullrequestreview-534486686)
> Remove rogue text

- CHANGELOG.md
- package.json
Merge release back into develop.
> [develop] Release 1.5.1

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- .github/workflows/stop_review.yml
> Use Github Actions for CI/CD instead of Gitlab 

- src/domain/api/generatedTypes/eventGroupQuery.ts
- src/domain/eventGroup/EventGroupPage.tsx
- src/domain/eventGroup/queries/eventGroupQuery.ts
Adjust event group events query to only show events that are available to the child.
> KK-686 | Fix event group events query

- src/domain/api/generatedTypes/eventGroupQuery.ts
- src/domain/eventGroup/EventGroupPage.tsx
- src/domain/eventGroup/queries/eventGroupQuery.ts
Adds a commit to the 1.6.0 release (which has not yet been created).
> Release 1.6.0 (extend)

- CHANGELOG.md
- package.json
- [#341](https://github.com/City-of-Helsinki/kukkuu-ui/pull/341) Use GitHub flow instead of GitFlow
- [#345](https://github.com/City-of-Helsinki/kukkuu-ui/pull/345) Privacy policy link
> Update documentation for release 1.6.1

- .github/workflows/review.yml
- browser-tests/pages/ssoLogin.ts
- browser-tests/utils/login.ts
Runs browser tests against the PR environment.
After this change developers will get more instant feedback from possible breakages in browser tests when it comes to their changes.
> Chore | Run browser tests against PR env

- CHANGELOG.md
- src/common/translation/i18n/fi.json
Add missing Finnish translations.
[KK-552](https://helsinkisolutionoffice.atlassian.net/browse/KK-552)
> KK-552 | Fix missing Finnish translations

- yarn.lock
Upgrades dependencies to resolve security issues, save for  immer in react-scripts, which does not have a backport to branch 3.x.x.
> Chore | Resolve security issues

- CHANGELOG.md
- browser-tests/utils/login.ts
- package.json
Adds documentation for 1.6.3 release.
> Chore | Document release 1.6.3

- .github/workflows/production.yml
Jira: DEVOPS-306
Simplifies integration configuration
> Redirect from www to apex domain

- .github/workflows/production.yml
- .github/workflows/review.yml
- .github/workflows/staging.yml
- browser-tests/childrenFeature.ts
Executed in a bit of a hurry. Needs to be done properly when there is more time.
> Disable front page corona info text

- browser-tests/utils/login.ts
- src/domain/api/client.ts
- src/domain/app/App.tsx
- src/domain/app/AppRoute.tsx
- src/domain/app/state/ui/UISelectors.ts
Two somewhat coupled authentication-related commits. The details are in the commit messages.
[Use new error codes when checking auth errors](https://helsinkisolutionoffice.atlassian.net/browse/813)
[Disallow API request until user is authenticated](https://helsinkisolutionoffice.atlassian.net/browse/811)
> KK-813 & KK-811 | Authentication improvements

- .eslintrc.json
- src/domain/event/EventParticipantsPerInvite.tsx
- src/domain/event/EventUtils.tsx
- src/domain/event/enrol/Enrol.tsx
- src/domain/event/enrol/enrol.module.scss
- src/domain/event/event.module.scss
- src/domain/event/partial/InfoItem.tsx
- src/domain/event/partial/OccurrenceInfo.tsx
- src/domain/event/partial/__tests__/__snapshots__/InfoItem.test.tsx.snap
- src/domain/event/partial/__tests__/__snapshots__/OccurrenceInfo.test.tsx.snap
- src/domain/event/partial/occurrenceInfo.module.scss
- src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap
KK-880. Added the venue address information to OccurrenceInfo used in the "enrol 2and the "enrolled page" and also added some style changes to OccurrenceInfo.
> Added venue address info to OccurrenceInfo

- src/domain/event/EventOccurrenceRedirect.tsx
> Fixed the back-button path on Ticketmaster enrolment page

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/api/generatedTypes/childEnrolmentCount.ts
- src/domain/child/ChildEnrolmentCount.tsx
- src/domain/child/queries/ChildEnrolmentCountQuery.ts
- src/domain/child/useChildEnrolmentCount.ts
- src/domain/event/EventEnrol.tsx
- src/domain/eventGroup/EventGroup.tsx
- src/domain/profile/children/ProfileChildrenList.tsx
- src/domain/profile/children/child/ProfileChild.tsx
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/events/__tests__/ProfileEventsList.test.tsx
- src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap
Make adjustments that were called for in KK-920.
[KK-920](https://helsinkisolutionoffice.atlassian.net/browse/KK-920)
[KK-840](https://helsinkisolutionoffice.atlassian.net/browse/KK-840)
> KK-920, KK-840 | Adjust behaviour relating to two event limit

- CHANGELOG.md
- src/common/components/modal/modal.module.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/api/generatedTypes/ChildEventInvitationLabelQuery.ts
- src/domain/child/ChildEventInvitationLabel.tsx
- src/domain/child/childEventInvitationLabel.module.scss
- src/domain/child/queries/ChildEventInvitationLabelQuery.ts
- src/domain/profile/Profile.tsx
- src/domain/profile/children/child/ProfileChild.tsx
- src/domain/profile/children/child/ProfileChildDetail.tsx
- src/domain/profile/children/child/profileChild.module.scss
- yarn.lock
* Don't show new event label if child can't enrol into upcoming events
* Include service description text on child page
* Fix modal alignment
[KK-920](https://helsinkisolutionoffice.atlassian.net/browse/KK-920)
> KK-920 | Fix comments made by Anna

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/event/enrol/__tests__/__snapshots__/SuccessToast.test.tsx.snap
Adds missing translations that Anna got for us.
> Add mising translations

- src/domain/api/generatedTypes/EnrolmentEventFields.ts
- src/domain/api/generatedTypes/childByIdQuery.ts
- src/domain/child/queries/ChildQueries.ts
- src/domain/profile/events/ProfileEventsList.tsx
- src/domain/profile/events/__tests__/ProfileEventsList.test.tsx
> Improvements to the implementation of Ticketmaster events

- azure-pipelines-release.yml
- azure-pipelines-test.yml
Azure DevOps pipeline files added, do not affect to github workflows 
> build: devops pipelines test and release DEVOPS-462

- CHANGELOG.md
- src/domain/app/App.tsx
KK-989. Redirect to the profile page when registrating with an existing credentials.
> Fix registration page redirect when profile exists

- CHANGELOG.md
- package.json
[KK-1000](https://helsinkisolutionoffice.atlassian.net/browse/KK-1000)
[KK-1000]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1000 | chore: update CHANGELOG.md and version to 1.11.0 after KK-1000

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
refs KK-999
[KK-999](https://helsinkisolutionoffice.atlassian.net/browse/KK-999)
[KK-999]: https://helsinkisolutionoffice.atlassian.net/browse/KK-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-999 | feat: update profile's service description texts

- .github/workflows/devops_review_tunnistamo.yml
- .gitignore
- azure-pipelines-review.yml
> Azure review pipelines

- browser-tests/pages/ssoLogin.ts
- browser-tests/utils/login.ts
Browser tests are failing on CI because login language is Finnish by some reason. Ensure login language is English.
> chore: browser test login language to English

- Dockerfile
Use ubi image as base
Helsinki-City ubi instructions
[Container images and Dockerfiles](https://helsinkisolutionoffice.atlassian.net/wiki/spaces/OS/pages/8298496186/Container+images+and+Dockerfiles)
[DEVOPS-560](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560)
[DEVOPS-560]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: dockerfile base on ubi image DEVOPS-560

- src/common/translation/TranslationUtils.ts
- src/domain/app/routes/useLocaleRouteNavigate.tsx
- src/domain/event/enrol/EnrolPage.tsx
> Fix the language sync handler

- src/assets/styles/main.scss
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/app/layout/PageLayout.tsx
- src/domain/constants.ts
- src/domain/cookieConsent/CookieConsent.tsx
> feat: cookie consent

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/app/__tests__/__snapshots__/Layout.test.tsx.snap
- src/domain/app/footer/Footer.tsx
- src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
- src/domain/app/routes/browserRouter.tsx
- src/domain/cookieConsent/CookieConsent.tsx
- src/domain/cookieConsent/CookieConsentPage.tsx
- src/domain/cookieConsent/__tests__/CookieConsentPage.test.tsx
- src/domain/cookieConsent/__tests__/__snapshots__/CookieConsentPage.test.tsx.snap
- Cookie consent page
- Link to footer
- Fix to the matomo logic in the cookie consent component
- Modal and page versions of the cookie consent
> feat: cookie consent page

- .gitignore
- package.json
- vitest.config.ts
- yarn.lock
> ci: configure the sonar reporters

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/i18nInit.ts
- src/common/translation/i18n/sv.json
- src/domain/api/generatedTypes/eventExternalTicketSystemPasswordCountQuery.ts
- src/domain/app/layout/InfoPageLayout.tsx
- src/domain/app/layout/utilityComponents/InfoTemplate.tsx
- src/domain/app/layout/utilityComponents/infoTemplate.module.scss
- src/domain/event/Event.tsx
- src/domain/event/EventRedirect.tsx
- src/domain/event/eventRedirect.module.scss
- src/domain/event/queries/eventExternalTicketSystemPasswordCountQuery.ts
NOTE:
- "yarn generate:graphql" is broken (See bug ticket KK-1065) and could
not be used to update the generated types. The types were updated
manually.
refs KK-1050, KK-1055
refs KK-1065 (reported "yarn generate:graphql" bug)
[KK-1050](https://helsinkisolutionoffice.atlassian.net/browse/KK-1050)
[KK-1055](https://helsinkisolutionoffice.atlassian.net/browse/KK-1055)
[KK-1065](https://helsinkisolutionoffice.atlassian.net/browse/KK-1065)
[KK-1050]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KK-1055]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KK-1065]: …
> feat: show "No free ticket system passwords" error & labels

- src/domain/home/form/__test__/HomePreliminaryFormUtils.test.ts
- src/domain/registration/form/RegistrationForm.tsx
- src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts
- src/domain/registration/state/RegistrationReducers.tsx
- src/domain/registration/types/RegistrationTypes.ts
> fix: registration form preferred language type

- codegen.ts
> fix: running generate:graphql, replace REACT_APP_API_URI -> VITE_API_URI

- package.json
- yarn.lock
TH-1303.
Fix the image links and change the language order.
> chore: upgrade the HCRC-lib to latest

- src/common/components/form/validationUtils.tsx
- src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
- src/domain/home/partners/__tests__/__snapshots__/HomePartners.test.tsx.snap
- src/domain/home/partners/__tests__/__snapshots__/PartnersLogoList.test.tsx.snap
- src/domain/home/partners/constants/PartnersConstants.tsx
refs KK-1068
[KK-1068](https://helsinkisolutionoffice.atlassian.net/browse/KK-1068)
[KK-1068]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1068 | fix: update Helsinki partner logo URLs

- src/common/components/cookieConfigProvider/CookieConfig.tsx
- src/common/components/cookieConfigProvider/CookieConfigProvider.tsx
- src/common/components/cookieConfigProvider/index.ts
- src/common/components/cookieConfigProvider/useCookieConfig.tsx
- src/domain/app/AppConfig.ts
- src/domain/app/BrowserApp.tsx
- src/domain/cookieConsent/CookieConsent.tsx
- src/index.tsx
About values of VITE_ORIGIN:
- [production](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines?path=/variables/kukkuu-ui-production.yml&_a=contents&version=GBmaster) is https://kummilapset.hel.fi
- [staging](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines?path=/variables/kukkuu-ui-staging.yml&_a=contents&version=GBmaster) is https://kukkuu-ui.stage.hel.ninja
- [testing](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines?path=/variables/kukkuu-ui-testing.yml&_a=contents&version=GBmaster) is https://kukkuu-ui.test.hel.ninja
- [review](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines?path=/variables/kukkuu-ui-development.yml&_a=contents&version=GBmaster) environments have https://kukkuu-ui$(reviewName).dev.hel.ninja …
> KK-1066 | fix(cookies): set cookie domain to hostname (e.g. kummilapset.hel.fi)

- src/domain/api/generatedTypes/graphql.tsx
- src/domain/profile/modal/EditMyEmailForm.tsx
- src/domain/profile/modal/RequestVerificationTokenButton.tsx
- src/domain/profile/modal/editProfileModal.module.scss
- src/domain/profile/mutations/requestEmailUpdateTokenMutation.ts
KK-1071 KK-1093 KK-1092
Depends on API changes of this PR: https://github.com/City-of-Helsinki/kukkuu/pull/346.
> feat: send the email update verification token to the new email

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/child/ChildEnrolmentCount.tsx
> fix: enrollements count

- package.json
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
- src/domain/home/form/__test__/__snapshots__/HomePreliminaryForm.test.tsx.snap
KK-1082
NOTE: Also fix the typecheck command
> fix: text correction on the frontpage

- src/common/translation/i18n/fi.json
- src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap
> fix: correct a compound word

- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
> fix: kids events search links

- README.md
- package.json
- yarn.lock
refs KK-1043
[KK-1043](https://helsinkisolutionoffice.atlassian.net/browse/KK-1043)
[KK-1043]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1043 | refactor: remove "update-translations" script & helsinki-utils package

- src/domain/app/routes/browserRouter.tsx
> fix: add missing page not found handler for pages under profile-path

- src/domain/profile/ProfileProvider.tsx
> fix: clear profile from redux when not authenticated

- README.md
> docs: remove create_superuser env variable

- src/domain/app/layout/pageLayout.module.scss
remove body margin same as in events monorepo apps
> KK-1171 | fix: body margin removed

- src/domain/app/layout/utilityComponents/heroLayout.module.scss
- src/domain/event/EventPage.tsx
- src/domain/event/event.module.scss
- src/domain/profile/ProfileProvider.tsx
- src/domain/profile/hooks/useProfileFetcher.ts
KK-1173.
- Add console infos to profile provider actions.
- add color to hero background when image is not given.
- profile fetcher should indicate that it is fully called also when an error occurs and not only when all succeeds.
- mobile view should show the back button for consistency and accessibility reasons.
> Miscallenous small fixes

- src/domain/registration/form/RegistrationForm.tsx
- src/domain/registration/form/__tests__/RegistrationForm.test.tsx
- src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
refs KK-1174
[KK-1174](https://helsinkisolutionoffice.atlassian.net/browse/KK-1174)
[KK-1174]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1174 | fix: disable editing email field in registration form

- src/domain/profile/events/AdditionalNotesCard.tsx
> fix: md editor and preview force light theme

- src/domain/app/footer/Footer.tsx
- src/domain/app/navigation/Navigation.tsx
- src/domain/app/routes/NavigateToLocalePath.tsx
- src/domain/app/useStaticLinks.tsx
- src/hooks/useCmsLanguageOptions.ts
- src/hooks/usePageQuery.ts
- src/utils/cmsUtils.ts
Fixes the localised pages routing issue. 
Note. Not all the pages have translations in test environment. If translated page is missing, user is redirected to the root of the website
[KK-1105](https://helsinkisolutionoffice.atlassian.net/browse/KK-1105)
[KK-1105]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1105 | fix: header menu localized routing

- src/domain/api/generatedTypes/graphql.tsx
KK-1108
Schema update after django-graphene upgrade in the API.
Fullfills the https://github.com/City-of-Helsinki/kukkuu/pull/390/
> fix: update graphql schema

- package.json
- src/domain/app/__tests__/__snapshots__/Layout.test.tsx.snap
- yarn.lock
[KK-1188](https://helsinkisolutionoffice.atlassian.net/browse/KK-1188)
[KK-1188]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: navigation render without data fetched

- src/domain/app/AppConfig.ts
> fix: helsinki profile url env var name

- docker-compose.yml
- src/index.tsx
> fix: test env mode

- src/domain/app/__tests__/__snapshots__/Layout.test.tsx.snap
- src/domain/app/navigation/UserNavigation.tsx
> fix: mobile navigation

- README.md
- docs/setup-keycloak.md
- docs/setup-local-kukkuu-api.md
- docs/setup-tunnistamo.md
> docs: update readme contentx (to be more structured and consistent)

- yarn.lock
Run "yarn upgrade" to upgrade yarn.lock versions
[KK-1356](https://helsinkisolutionoffice.atlassian.net/browse/KK-1356)
[KK-1356]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1356 | Run "yarn upgrade" to upgrade yarn.lock versions

- README.md
KK-1378.
1. Document git commit hooks and husky. 
2. Document releases, deploying and release-please
> Document git commit hooks and deployments

- compose.yaml
> chore: docker compose production port forward

- package.json
- src/common/time/TimeConstants.ts
- src/common/time/utils.tsx
- src/domain/event/EventUtils.tsx
- yarn.lock
KK-1253.
Install `date-fns-tz`, so we can fix all the dates and times in a
specific timezone.
> fix(time-utils): fix all dates and times to Helsinki timezone

- src/domain/app/AppConfig.ts
KK-1408
NOTE: Also the pipeline is configured so that the renewal is enabled.
> chore: enable OIDC renewal by default

- src/domain/api/generatedTypes/graphql.tsx
Update graphql schema after viewFamilies permission adding
[KK-1403](https://helsinkisolutionoffice.atlassian.net/browse/KK-1403)
[KK-1403]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1403 | Update graphql schema after viewFamilies permission adding

- index.html
Add localhost:*, 127.0.0.1:* to CSP connect-src to fix local development
[KK-1407](https://helsinkisolutionoffice.atlassian.net/browse/KK-1407)
[KK-1407]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1407 | Add `localhost:*`, `127.0.0.1:*` to CSP connect-src to fix local development

- src/domain/event/Event.tsx
Show "can't enrol" notification also with external ticket systems.
Was previously shown only for events using internal ticket systems.
[KK-1412](https://helsinkisolutionoffice.atlassian.net/browse/KK-1412)
[KK-1412]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1412 | Show "can't enrol" notification also with external ticket systems

- src/domain/event/EventRedirect.tsx
Show "can't enrol" notification in EventRedirect component.
Previously EventRedirect component allowed a person to fetch
an external ticket system password even if they couldn't enrol
into the event.
Now a "can't enrol" notification will be shown if the person can't
enrol into the event and no button for fetching the external ticket
system password is shown.
[KK-1412](https://helsinkisolutionoffice.atlassian.net/browse/KK-1412)
Example URL used in local testing:
http://localhost:3000/fi/profile/child/Q2hpbGROb2RlOjJlYmI5NDM0LTU5NDktNGI4OS04YjEwLTIzNjI0YTI3MjZjOQ==/event/RXZlbnROb2RlOjg=/redirect
[KK-1412]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1412 | Show "can't enrol" notification in EventRedirect component

- index.html
> fix: add digiaiiris.com to csp

- index.html
> fix(csp): allow cms images

- src/common/components/card/Card.tsx
- src/common/translation/i18n/en.json
- src/common/translation/i18n/fi.json
- src/common/translation/i18n/sv.json
- src/domain/app/navigation/UserNavigation.tsx
- src/domain/event/EventRedirect.tsx
- src/utils/__tests__/cmsUtils.test.ts
- src/utils/cmsUtils.ts
Fix SonarCloud reliability issues, see commits for details.
Specifically fix the 5 reliability issues that dropped the reliability rating to C:
- ![image](https://github.com/user-attachments/assets/eac580bd-0c01-4346-b5de-b9293d9ee1f5)
- [KK-1416](https://helsinkisolutionoffice.atlassian.net/browse/KK-1416)
- [SonarCloud issues](https://sonarcloud.io/summary/overall?id=City-of-Helsinki_kukkuu-ui&branch=master)
- ![image](https://github.com/user-attachments/assets/ea75824e-9da1-4043-952a-e7d178aa4e6e)
Using [SonarQube for IDE plugin for PyCharm](https://plugins.jetbrains.com/plugin/7973-sonarqube-for-ide) locally in PyCharm.
[KK-1416]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1416 | Fix SonarCloud reliability issues

- src/domain/headlessCms/persistor.ts
> docs: add react-router link note to apollo cache persistor

- .github/workflows/ci.yml
- sonar-project.properties
> ci: add Github CI workflow

- src/domain/child/__tests__/ChildEnrolmentCount.test.tsx
- src/domain/profile/events/__tests__/AdditionalNotesCard.test.tsx
KK-1419. Some more tunings to https://github.com/City-of-Helsinki/kukkuu-ui/pull/667.
> Some more tunings to #667

- src/common/components/alert/__tests__/AlertModal.test.tsx
- src/common/components/button/__tests__/AnchorButton.test.tsx
- src/common/route/utils/__tests__/replaceLocaleInPathname.test.ts
- src/domain/child/__tests__/ChildEnrolmentCount.test.tsx
- src/domain/child/__tests__/ChildEventInvitationLabel.test.tsx
- src/domain/profile/events/AdditionalNotesCard.tsx
- src/domain/profile/events/__tests__/AdditionalNotesCard.test.tsx
- src/domain/profile/modal/__tests__/RequestVerificationTokenButton.test.tsx
- src/domain/profile/subscriptions/ManageSubscriptionsForm.tsx
- src/domain/profile/subscriptions/__tests__/ManageSubscriptions.test.tsx
Tune tests, use more getByRole, test for mutations etc.
- [KK-1419](https://helsinkisolutionoffice.atlassian.net/browse/KK-1419)
- PR #665
Ran locally:
- `yarn lint`
- `yarn typecheck`
- `yarn test`
And all of them passed.
[KK-1419]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KK-1419 | Tune tests, use more getByRole, test for mutations etc

- .github/workflows/ci.yml
- .github/workflows/release-please.yml
- pipelines/kukkuu-ui-dev.yml
- pipelines/kukkuu-ui-review.yml
Refs: [KK-1427](https://helsinkisolutionoffice.atlassian.net/browse/KK-1427)
[KK-1427]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: default branch name change

- package.json
- yarn.lock
> chore: update testcafe
