City-of-Helsinki/kukkuu-ui

src/domain/api/__tests__/client.test.ts
src/domain/api/generatedTypes/ChildrenQuery.ts
src/domain/api/generatedTypes/globalTypes.ts
src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
src/domain/registration/form/RegistrationForm.tsx
src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts

This PR seems to work with the backend and only one child. 
Now that the backend has a more "complete" schema it might be possible to create the mutations in a more fancy apollo + graphql + typescript 2019 kinda way.

KK-117 | Multiple children in graphql mutation

---

src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts

submitChildrenAndGuardian should query relationships.edges.node.type instead
of relationship.type because the latter will be removed to achieve consistency.

Update mutation to support change in schema

---

src/common/components/form/__tests__/validationUtils.tests.tsx
src/common/components/form/validationUtils.tsx
src/domain/child/ChildUtils.ts
src/domain/child/modal/ChildFormModal.tsx
src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap
src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
src/domain/registration/state/RegistrationReducers.tsx
src/domain/registration/types/RegistrationTypes.ts

This works for me both when registering and adding children. 
Another way to fix this is to open `src/domain/registration/form/partial/ChildFormField.tsx` and change line 92 from 
```name={`children[${childIndex}].relationship.type`}```
to
```name={`children[${childIndex}].relationship`}```
That is a smaller PR but I prefer this one that deletes lines instead.

KK-153 | Use correct relationship format for submit add child mutations

---

src/domain/child/modal/ChildFormModal.tsx
src/domain/child/modal/__tests__/__snapshots__/ChildFormModal.test.tsx.snap

Make sure modal local state is reset anytime modal was toggled.
One does not simply: Unmounted element will not reset hook state automatically. Its state still persisted

KK-174 | Ensure to toggle off nonEligible hook state when close modal

---

src/common/components/input/input.module.scss

This happened especially with homePreliminaryForm on Firefox.
Before:
After:

KK-239 | Prevent horizontal scrolling/overflow on mobile

---

public/index.html

Twitter and Facebook require a fully qualified url for these tags. Facebook still seems to work, but Twitter won't load the image.

KK-214 | Use fully qualified url for og:image and twitter:image

---

.travis.yml
CHANGELOG.md
package.json
yarn.lock

Latest CRA, node-sass and apollo
Current security happen from Apollo basically, have yarn as dependency

Bumping dependencies

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/profile/children/child/ProfileChild.tsx
src/domain/profile/children/child/profileChild.module.scss

At the moment we don't get information from the backend about new invitations so this will only show if you set `availableEvents` to `true`. Advantage of this solution: If we deploy a new version, it will not affect end users.

KK-276 | New invitation button on children list

---

src/domain/api/generatedTypes/addNewChild.ts
src/domain/api/generatedTypes/eventQuery.ts
src/domain/api/generatedTypes/profileQuery.ts
src/domain/api/generatedTypes/submitChildrenAndGuardian.ts
src/domain/api/generatedTypes/updateChild.ts
src/domain/api/generatedTypes/updateMyProfile.ts
src/domain/child/mutation/ChildMutation.ts
src/domain/event/queries/eventQuery.ts
src/domain/profile/children/child/ProfileChild.tsx
src/domain/profile/children/child/modal/ProfileChildDetailEditModal.tsx
src/domain/profile/mutations/updateMyProfileMutation.ts
src/domain/profile/queries/ProfileQuery.ts
src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts

Bonus: 
* Add id to all graphql queries
* Do not rely on translation field on event (profileQuery_myProfile_children_edges_node_availableEvents_edges_node_translations)

KK-332 | Make it possible to update children again

---

src/common/components/modal/modal.module.scss

Modal header should be centered horizontally

---

src/domain/child/modal/ChildFormModal.tsx
src/domain/registration/notEligible/NotEligibleUtils.ts
src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts

This is a slight improvement over the current situation - we don't care what people type in the city field. We will store the postal code, though. 
Longer term solution involves either storing the city in the back end or looking the city up based on the postal code.

KK-317 | Don't check city eligibility when editing a child

---

src/index.tsx

I was just reminded that process.env.NODE_ENV can is set to test when we run tests, and we absolutely do not want to send sentry events for errors in tests. 
NODE_ENV is either production, test or development, as mentioned here (so both our staging and production envs have NODE_ENV set to production)
> When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.
https://create-react-app.dev/docs/adding-custom-environment-variables/

Only send events from production build to sentry

---

src/common/components/error/Error.tsx
src/common/components/error/error.module.scss
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/auth/OidcCallback.tsx
src/domain/event/EventIsEnrolled.tsx
src/domain/event/enrol/Enrol.tsx
src/domain/profile/Profile.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx

Bonus: Add a <ErrorMessage /> component for less code duplication.
How to test: 
1. Use a non-local Tunnistamo
2. Set your device time to be minimum 5 minutes early or late
3. Log in
The strings for the error messages is still TODO, but those translations will be updated later.

KK-268 | Inform user better when login fails due to device time being off

---

src/domain/api/client.ts
src/domain/app/App.tsx
src/domain/auth/authenticate.ts
src/domain/auth/getAuthenticatedUser.ts
src/domain/auth/route/PrivateRoute.tsx
src/domain/auth/state/AuthenticationSelectors.ts
src/domain/auth/state/BackendAuthenticationReducer.ts
src/domain/auth/types/BackendAuthenticationTypes.ts
src/domain/auth/userManager.ts
src/domain/event/Event.tsx
src/domain/event/enrol/Enrol.tsx
src/domain/event/modal/UnenrolModal.tsx
src/domain/profile/Profile.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/registration/notEligible/NotEligibleUtils.ts

* Refactor how we fetch backend api token now that we have silent renew
* If a user comes from a link to a "deep" page in their profile, automatically log them in and redirect to it
* Console.error for all errors. NOTE: `yarn build` strips console statements out so no need to worry about end users
* Fix spelling error in code comment & add some typing

KK-443, KK-261 | Automatically log in users, fix silent renew & login across tabs

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/EventEnrol.tsx
src/domain/event/EventOccurrence.tsx
src/domain/event/partial/OccurrenceInfo.tsx
src/domain/event/partial/__tests__/__snapshots__/OccurrenceInfo.test.tsx.snap
src/domain/profile/Profile.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap

On the user profile page, child detail page, event sign up and confirmation pages we use icons to convey information, and they have been missing alt text to help users with screen readers.

Improve accessibility by adding alt texts for icons

---

.gitlab-ci.yml
package.json
yarn.lock

Looking at the devops documentation I realised that postgres is enabled by default, and I think we've had it enabled for the staging environment all this time. 
Production is still in the "classic" infra, but good to disable it already now!

Remove postgres from this front end project's ci/cd

---

src/common/localization/setLocale.tsx
src/common/translation/i18n/i18nInit.ts
src/domain/event/EventOccurrence.tsx
src/domain/event/__tests__/EventOccurrence.test.tsx
src/domain/event/__tests__/__snapshots__/EventOccurrence.test.tsx.snap
src/setupTests.ts

Moment uses the `en` locale by default. I changed the bootstrap code so that moment's locale and the language of the application are kept in sync.
As a small encapsulation measure I added a `setLocale` utility function which can possibly be used to configure other localisation dependent libraries (like numbers).
The file structure is maybe a bit odd here. I don't have a good intuitive feel for how internationalisation and localisation differ so I don't know which is the correct terminology here. But I did think that it didn't belong under `translations`.

KK-527 | Use Finnish time format

---

src/common/__tests__/__snapshots__/commonUtils.tests.tsx.snap
src/common/__tests__/commonUtils.tests.tsx
src/common/commonUtils.tsx

Previously only CRLF was treated as a line break causing problems with content coming from Kukkuu admin.

KK-529 | Allow also LF as a line break

---

CHANGELOG.md
package.json
src/assets/styles/variables.scss
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/api/generatedTypes/profileChildrenQuery.ts
src/domain/app/App.tsx
src/domain/app/header/userDropdown/UserDropdown.tsx
src/domain/app/layout/InfoPageLayout.tsx
src/domain/app/layout/infoPageLayout.module.scss
src/domain/auth/WrongLoginMethod.tsx
src/domain/auth/route/ProtectedRoute.tsx
src/domain/auth/useLogout.ts
src/domain/profile/queries/ProfileChildrenQuery.ts
src/domain/profile/route/ProfileChildRoutes.tsx
src/domain/profile/route/ProfileRoute.tsx
src/domain/profile/route/useIsChildOfProfile.ts
yarn.lock

The user can login to the service using other services like Google or
Facebook. Once they have logged in using a service, they must always
use the same one if they want to access the "kukkuu" account that is
created then.
Sometimes users login with a service they did not use during their
initial sign up process. In this scenario, they are not able to access
their original data.
A usecase that's especially problematic is when the user receives a
link into their mail they can use to sign up their child into an event.
If they login by using the wrong service, they end up in a view that
doesn't work and gives little in the way of clues as to why.
After this commit, the user would be redirected into the wrong login
method page, which guides them to sign in again.
----
I've tested these things …

KK-540 | Redirect to error view when accessing unknown child

---

src/common/time/TimeConstants.ts
src/domain/event/Event.tsx
src/domain/event/EventOccurrence.tsx
src/domain/event/__tests__/__snapshots__/EventOccurrence.test.tsx.snap
src/domain/event/partial/__tests__/__snapshots__/OccurrenceInfo.test.tsx.snap
src/domain/profile/events/__tests__/__snapshots__/ProfileEventsList.test.tsx.snap

- Wen't through every format executed with moment and replaced strings with constants.
- Changed `DEFAULT_DATE_FORMAT ` not show leading zeroes.

KK-541 | Event occurrence time is shown incorrectly

---

src/domain/auth/OidcCallback.tsx

If push is used instead of replace, the callback page is retained
within the history. The user can then access it by using the back
button, which will lead to an error.
These errors are problematic, because they flood Sentry and may be
hiding other usecases which lead to the same error. The user experience
when backing into the callback page is also poor in general and may
mislead the user.
The original `.push` code was added in conjunction with some registration flow improvements. I tested that registration still works as expected.

KK-542 | Use replace when redirecting user according to state

---

CHANGELOG.md
src/common/components/card/Card.tsx
src/common/components/card/card.module.scss

The event invitation card should no longer display two links on mobile. The button element should also be displayed last.

KK-551 | Hide second link on event invitation card

---

CHANGELOG.md
src/common/components/dropdown/Dropdown.tsx
src/domain/app/header/userDropdown/UserDropdown.tsx

Previously the profile menu relied on the `aria-label` attribute in order to communicate its state. Moreover, the naming applied to it was relatively vague. It was simply named as "menu".
In these changes I've adjusted the use of aria-attributes. I've added `aria-haspopup` and removed the use of state within the `aria-label`. The `aria-expanded` attribute already communicates this. We've also adjusted the button naming. Instead of "menu" the accessible content is now read as _label of button_ + _label of icon_. In the case of the user menu, for instance, 
>George profile menu
I checked the mobile menu as well while doing these changes. Unfortunately it ended up being less simple than the regular navigation changes. I think I need more context before I am able to make a proper fix.

KK-546 | Fix vague naming of profile menu for screen readers

---

CHANGELOG.md
src/domain/event/enrol/enrol.module.scss
src/domain/event/event.module.scss

- Event page should no longer overflow on mobile. In other words, the page should not have a horizontal scroll bar on mobile.
- Buttons and event information should now be extended to page margins on mobile

KK-550 | Fix mobile layout for event enrollment

---

CHANGELOG.md
src/domain/app/header/userDropdown/UserDropdown.tsx
src/domain/profile/Profile.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/profile/hooks/useProfile.ts

Previously the logged in user's profile was synced into the redux state
when the details for their user menu were fetched. On mobile, this menu
is not rendered by default, so their details were not ever synced and
they ended up seeing an empty list of children instead.
It's a bit odd that the user details are stored in two places: (1) in
Apollo's state and in (2) Kukkuu's redux state. I think that ideally
this duplication would not exist. But because I don't understand enough
of the context of the application yet, I didn't remove this
duplication entirely.
As a fix I created the useProfile hook. It fetches the profile and
stores it into the redux state--roughly the logic that was contained
within the user menu before. After this change, the profile is loaded
whenever it is accessed so …

KK-549 | Fix empty child list on mobile

---

CHANGELOG.md
src/domain/profile/children/ProfileChildrenList.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/profile/hooks/useProfile.ts

The child list used data from the redux store. The child add modal
relied on Apollo's refetchQueries to update related data. However,
refetched queries are not at any point synced into the redux store.
This behaviour may have broken in 054e284 where we changed the
synchronising mechanism between Apollo and redux from useEffect to
a callback. The callback is only fired when that particular hook makes
a query. The data the hook returns in turn changes when the cached data
changes. In this way the useEffect approach will more consistently keep
the two states in sync.
Using useEffect in such a way is an anti-pattern. Apollo likely
provides some other mechanism which allows us to subrscibe to state
changes, but I doubt that they are worth it when we can just as well
use source the data from …

KK-563 | Fix child list not updating after adding a new child

---

CHANGELOG.md
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/enrol/Enrol.tsx
src/domain/event/enrol/EnrolConstants.ts

When the user attempts to enrol a child into an event the child is already enrolled in they will be redirected to the event page and a warning notification will be shown to them.
While logged in into a kukkuu account that has a child
1) Go to child page
2) Go to event page
3) Select occurrence
4) Copy URL
5) Paste URL into a new tab
6) In the first tab, enrol
7) in the second tab, enrol
(In the second tab) Expect to be redirected into the event page and see a warning toast.

KK-567 | Handle child already enrolled error

---

src/domain/event/mutations/unenrolOccurrenceMutation.ts

I wasn't able to understand why the crash did happen in detail. As a
result of trial and error, I was able to find out that the crash
happens because the mutation I update here and the query updated
in f3900586 fall out of sync.
This may be due to:
- Some special behaviour in Apollo I do not understand
- The interop between redux and Apollo
- Some other underlying bug that this configuration reveals, but I
wasn't able to pinpoint

KK-573 | Fix application crash when unenrolling

---

CHANGELOG.md
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/child/form/ChildForm.tsx
src/domain/registration/form/RegistrationForm.tsx

Previously the UI had a more lenient validation for the postal code
compared with the backend. This made it possible for users to submit
the form with data that was considered invalid by the backend.

KK-561 | Fix postal code validation

---

src/common/test/initModal.ts
src/common/test/testingLibraryUtils.tsx
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/EventNotificationSubscriptionModal.tsx
src/domain/event/EventOccurrence.tsx
src/domain/event/EventOccurrenceNotificationControlButton.tsx
src/domain/event/__tests__/EventOccurrence.test.tsx
src/domain/event/__tests__/__snapshots__/EventOccurrence.test.tsx.snap
src/domain/event/enrol/Enrol.tsx
src/domain/event/enrol/EnrolConstants.ts
src/domain/event/enrol/EnrolPage.tsx
src/domain/event/enrol/__tests__/Enrol.test.tsx
src/domain/event/eventOccurrence.module.scss
src/domain/event/eventOccurrenceNotificationControlButton.module.css
src/domain/event/useSubscribeToFreeSpotNotificationMutation.tsx
src/domain/event/useUnsubscribeFromFreeSpotNotificationMutation.ts

This PR contains code changes which try to generalise the notification control button enough so that it can be shared between the enrolment and occurrence list pages. Currently the component contains the subscription, unsubscription and subscription confirmation modal components. Depending on the status of the user's subscription, one of the two buttons is shown. Because the confirmation modal should always be shown when subscribing, I thought that it'd be convenient to also include it into this component. The downside is that the modal is declared multiple times, although that shouldn't be a huge caveat.
I also refactored the tests I previously implemented tests with `enzyme` that I now replaced with `testing-library`, because `enzyme` is inconvenient for integration level test cases.
In …

KK-513 | Fix free spot notification subscriptions

---

CHANGELOG.md
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/api/useDefaultErrorHandler.ts
src/domain/api/utils/getIsError.ts
src/domain/event/EventConstants.ts
src/domain/event/useSubscribeToFreeSpotNotificationMutation.tsx

Previously two error messages were not handled for subscriptions: `ALREADY_SUBSCRIBED_ERROR` and `OCCURRENCE_IS_NOT_FULL_ERROR`. This PR add error handling logic which should help the user recover from these errors.
After this change users facing the `ALREADY_SUBSCRIBED_ERROR` no longer see a generic error message. Instead the page is refreshed which should update stale data and show, that what they want, to subscribe to notifications, is already taking place. In other words we don't directly inform the user about the error at all.
`OCCURRENCE_IS_NOT_FULL_ERROR` can take place when the user attempts to subscribe to notifications for an event that has free places left. This can potentially happen when user 1 loads the page and leaves it open for a while, and in the meanwhile user 2 cancels …

KK-585 | Handle unhandled error codes

---

CHANGELOG.md
src/domain/app/header/userDropdown/UserDropdown.tsx
src/domain/profile/hooks/useProfile.ts

In these changes I add a skip condition to the `useProfile` hook. This is then used in the `UserDropdown` to stop uses of this hook from resulting in redirects. The idea is that this component already knows how to render itself in each profile condition--it does not need the profile to function. Instead, other calls of this hook which do require the profile are given the responsibility to cause a redirect.
This resolves the root cause of the fixed bug as well--user's are no longer redirected away from the `registration/form` page. Previously the `useProfile` call in the menu could cause for this to happen depending on the order in which calls finished.
[KK-586](https://helsinkisolutionoffice.atlassian.net/browse/KK-586)
I've tested this manually in order to avoid mocking the API. This is …

KK-586 | Fix users being asked for their child's birthday twice

---

CHANGELOG.md
src/domain/event/enrol/EnrolPage.tsx

In these changes we start to use a specific URL when we direct users back to event selection (occurrence list page). We also change the redirection urls from language naive to language aware versions, which allows us to avoid doing unnecessary redirects, which cause the UI to feel slow.
When the user accessed the enrolment confirmation view through an email invitation link and chose to back to event selection, they would be thrown out of the application entirely. This was because the back to event selection button used `history.goBack` instead of the event page url.
[KK-601](https://helsinkisolutionoffice.atlassian.net/browse/kk-601)
This has been tested manually by opening the enrolment confirmation page in place of an unrelated tab, pressing the back to event selection button, and …

KK-601 | Fix back to event selection button

---

CHANGELOG.md
src/domain/auth/OidcCallback.tsx

This change adds contextual data to Sentry error capture. It stores a boolean value into Sentry that describes whether the user is already logged in.
This data will allow us to test our hypothesis for why Sentry captures so many "State not found errors". These errors happen when users access the `/callback` view with a `state` parameter that doesn't point into an oidc object in local storage.
Our null hypothesis (H<sub>0</sub>) is that the mean of signed users receiving this error is less or equal to mean of the amount of non-signed in users who receive it.
Our alternative hypothesis (H<sub>a</sub>) is that the mean of signed in users receiving this error is greater than the mean of non-signed in users who receive it.
We will compare the means without any rigorous application of …

Add more context to "No matching state" error

---

CHANGELOG.md
src/domain/languages/LanguagesCombobox.tsx

Hides the "clear" button from the language spoken at home select in the profile update dialog and registration view.
The "clear" button is superfluous because users will likely never select so many options that it'd be helpful.
[KK-606](https://helsinkisolutionoffice.atlassian.net/browse/KK-606)
I've checked that the clear all button was no longer shown in the profile edit modal.
As a signed in user in your profile view
1. Click edit profile
1. If you do not have languages spoken at home selected, select one
1. Expect to not see an "x" button for clearing all options

KK-606 | Hide clear all button

---

.gitignore
.testcaferc.json
.travis.yml
README.md
browser-tests/childrenFeature.ts
browser-tests/godchildrenProfileFeature.ts
browser-tests/pages/childrenProfilePage.ts
browser-tests/pages/godchildrenProfilePage.ts
browser-tests/pages/login.ts
browser-tests/pages/ssoLogin.ts
browser-tests/utils/getDropdownOption.ts
browser-tests/utils/login.ts
browser-tests/utils/routes.ts
browser-tests/utils/settings.ts
package.json
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/profile/children/child/ProfileChild.tsx
yarn.lock

Adds support for creating browser tests. Adds initial browser tests for guardian's own profile and their children.
Ive configured Travis to run these tests daily.
I've added initial tests for two "features". The profile of the guardian and some of the features that come to controlling one's child.
Here's a test run that includes the browser tests in Travis:
* https://travis-ci.com/github/City-of-Helsinki/kukkuu-ui/jobs/443317934
Unfortunately the tests will not pass until this PR is merged.

Chore | Add initial browser tests

---

CHANGELOG.md
src/domain/child/form/ChildForm.tsx
src/domain/child/form/__tests__/ChildForm.test.jsx

Adds the `noValidate` attribute to the child form. This ignores browser validation so that it doesn't block our custom validation.
I also refactored the view to use `<Form />` from `formik` which automatically binds the `onSubmit` and `onReset` events.
[KK-661](https://helsinkisolutionoffice.atlassian.net/browse/KK-661)
I've tested this manually. I don't think that a meaningful test can be written to check the actual user interaction. Instead I tested that the child's form element has `noValidate` set to `true`.
As a logged in user
1. Click add a new child
1. Fill a the birthday 02-02-2010
1. Fill other required fields
1. Submit
1. Expect to see a view where you are being told that your child is not eligible

KK-661 | Do not browser validate child form

---

src/domain/child/form/ChildForm.tsx
src/domain/child/form/__tests__/ChildForm.test.jsx

Hides the city input when editing a child.
[KK-658](https://helsinkisolutionoffice.atlassian.net/browse/KK-658)
I've added a unit test that checks the omission of the field.
As a logged in user
1. Navigate to one of your children
1. Click the edit information button
1. Expect not to see the city control

KK-658 | Hide city input when editing a child

---

CHANGELOG.md
browser-tests/utils/settings.ts
src/common/components/giveFeedbackButton/GiveFeedbackButton.tsx
src/common/components/giveFeedbackButton/giveFeedbackButton.module.scss
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/profile/Profile.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx

Adds a link to a feedback form that will be removed at some point. I needed to pull button styles from `hds-core` because I think that there's no link button in HDS.
[KK-660](https://helsinkisolutionoffice.atlassian.net/browse/KK-660)
I've tested this by hand.
Expect to see a link-button in profile and child profile pages

KK-660 | Add temporary link for giving feedback

---

CHANGELOG.md
package.json

- [#330](https://github.com/City-of-Helsinki/kukkuu-ui/pull/330) Support for event groups
- [#332](https://github.com/City-of-Helsinki/kukkuu-ui/pull/332) Logo of Kaapeli to the home page

[develop] Release 1.6.0

---

.github/workflows/CI.yml
.github/workflows/production.yml
.github/workflows/staging.yml
.gitlab-ci.yml
CHANGELOG.md

Transitions this repository into using GitHub flow that is recommended in best practices.
Because a new version was just release, and the development and master branches are in sync as content goes, this is an easy time to make the transition.
[Best Practices: Version Control](https://dev.hel.fi/version-control#git-workflow)

Chore | Use GitHub flow instead of GitFlow

---

package.json
yarn.lock

This allows immer to be upgraded to a secure version.

Chore | Update @reduxjs/toolkit from 1.4.0 to 1.5.0

---

CHANGELOG.md
package.json

Changes the translation sheet to one that is managed under the XO's account.
[KK-713](https://helsinkisolutionoffice.atlassian.net/browse/KK-713)
I changed the sheet id and rant he translation script. The script worked and did not cause any changes = I'm happy.
You can try running the script locally. Hit me up if you want to edit the sheet.

KK-713 | Use translation sheet managed by executive office

---

CHANGELOG.md
browser-tests/childrenFeature.ts
browser-tests/eventGroupsFeature.ts
browser-tests/pages/godchildrenProfilePage.ts
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/profile/children/child/ProfileChild.tsx

Use same content for screen reader as for visual users.
Removes aria-label from children in child list so that the content of the button is read aloud with screen readers.
Refactors browser test because the change caused some selector patterns to become unusbale.
[KK-682](https://helsinkisolutionoffice.atlassian.net/browse/KK-682)
With VoiceOver and Safari.
Expect screen reader users to have access to all the information visual users do.

KK-682 | Fix children list screen reader content

---

CHANGELOG.md
src/common/test/testingLibraryUtils.tsx
src/domain/event/EventOccurrence.tsx
src/domain/event/__tests__/EventOccurrence.test.tsx
src/domain/event/__tests__/__snapshots__/EventOccurrence.test.tsx.snap
src/domain/event/eventOccurrence.module.scss

Fixes incorrect tab order in occurrence list when using a mobile sized screen.
Implements a custom view for mobile so that table headers and rows match.
[KK-684](https://helsinkisolutionoffice.atlassian.net/browse/KK-684)
I've used VoiceOver and Safari to test this.
One thing worth noting is that the technical implementation uses table, but override's its display values in which case the screen reader is not able to see a table.
The layout on mobile looks like it could be difficult to reproduce using tables do I haven't attempted to fix the semantics here.

KK-684 | Fix incorrect tab order in occurrence list

---

CHANGELOG.md
src/common/components/form/fields/terms/TermsField.tsx

Fix low contract in checkbox tickmark.
[KK-698](https://helsinkisolutionoffice.atlassian.net/browse/KK-698)

KK-698  | Fix low contrast in checkbox

---

CHANGELOG.md
package.json

- [#361](https://github.com/City-of-Helsinki/kukkuu-ui/pull/361) Links into partner logos
- [#349](https://github.com/City-of-Helsinki/kukkuu-ui/pull/349) Into using a translation sheet that is managed by executive office
- [#350](https://github.com/City-of-Helsinki/kukkuu-ui/pull/350) Adjusted some translations
- [#360](https://github.com/City-of-Helsinki/kukkuu-ui/pull/360) Service description to allow for children born after 2020
- [#354](https://github.com/City-of-Helsinki/kukkuu-ui/pull/354) [Accessibility] Use same text content for screen readers and visual users in child list
- [#357](https://github.com/City-of-Helsinki/kukkuu-ui/pull/357) [Accessibility] Announce title on page changes
- [#356](https://github.com/City-of-Helsinki/kukkuu-ui/pull/356) [Accessibility] Incorrect tab …

Document release 1.6.2

---

src/domain/auth/authenticate.ts

Users are receiving unexpected network errors when registering. We suspect that the error fails to be passed into Sentry at this point in code.

Capture network errors into Sentry when authenticating

---

CHANGELOG.md
package.json

Adds documentation for release 1.6.4
--------------
- [#370](https://github.com/City-of-Helsinki/kukkuu-ui/pull/370) Fix broken authentication: Users accessing the www prefixed address of the production version of the service will now be redirected to the service address without the www prefix

Document release 1.6.4

---

src/domain/api/generatedTypes/eventOccurrenceQuery.ts
src/domain/api/generatedTypes/eventQuery.ts
src/domain/api/generatedTypes/occurrenceQuery.ts
src/domain/event/EventIsEnrolled.tsx
src/domain/event/enrol/EnrolPage.tsx
src/domain/event/modal/UnenrolModal.tsx
src/domain/event/queries/occurrenceQuery.ts
src/domain/eventGroup/EventGroupPage.tsx

Introduces a check which redirects users into the profile page when there are no events to enrol into on the event group page. We assume that when there are no events, something is either wrong or the user has already enrolled.
Adds a query refetching mechanism that refetches the event group page query so that the amount of available event is correctly updated when a user enrols into an event.

KK-773 | Prevent users from accessing event group enrolment userpath after having been enrolled into an event

---

src/domain/event/modal/UnenrolModal.tsx

The profile query is refetched after executing the unenrol mutation to update the child's enrolments. However, the unenrol mutation's refetch queries weren't awaited for, which resulted in a situation where the refetched profile query was still not completed when there was already a redirection to the profile page where the child's enrolments were then updated to the Redux store with old data.
In practice this meant a user could not go back to an event page after unenrolling at least when the event was in an event group.
As a side note, I really think we should try to get rid of Redux.

KK-775 | Fix profile refetching after unenrol mutation

---

CHANGELOG.md
src/common/components/modal/modal.module.scss

Fix inaccessible modal content.
Modals did not scroll, which caused content on some larger modals to become inaccessible.
[KK-904](https://helsinkisolutionoffice.atlassian.net/browse/KK-904)

KK-904 | Scroll modal when it overflows viewport

---

src/domain/app/footer/Footer.tsx
src/domain/headlessCms/HeadlessCmsPage.tsx
src/domain/headlessCms/headlessCmsPage.module.scss

Kukkuu's footer overflows its container by a bit. Offset this when using the footer on a headless cms page.

Fix footer spacing

---

src/common/route/useSyncLanguageBetweenI18nAndReactRouter.ts
src/common/route/utils/__tests__/getPathname.test.ts
src/common/route/utils/getPathname.ts
src/common/translation/i18n/i18nInit.ts

Previously logging in would fail when users used some other language than Finnish.
When the user logged in while using English:
1) They get redirected from Tunnistamo to `/callback#...`
2) i18next detects that user locale is `en` from a cookie
3) i18next language is changed
4) `languageChanged` hook is fired in `src/common/translation/i18n/i18nInit.ts`
5) User is redirected into `/callback` (missing hash)

Fix login when using some other language than Finnish

---

src/common/commonUtils.tsx
src/common/components/button/LinkButtonBase.tsx
src/common/components/button/buttonOverrides.module.scss
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/api/generatedTypes/ticketmasterEventQuery.ts
src/domain/event/EventOccurrence.tsx
src/domain/event/EventOccurrenceRedirect.tsx
src/domain/event/EventPage.tsx
src/domain/event/TicketmasterEventIsEnrolled.tsx
src/domain/event/TicketmasterPassword.tsx
src/domain/event/eventOccurrenceRedirect.module.scss
src/domain/event/partial/__tests__/package.json
src/domain/event/queries/ticketmasterEventQuery.ts
src/domain/event/ticketmasterEventIsEnrolled.module.scss
src/domain/event/ticketmasterPassword.module.scss
src/domain/profile/events/ProfileEventsList.tsx
src/domain/profile/route/ProfileChildRoutes.tsx

Added a new event page for Ticketmaster events that users have "enrolled" (obtained a password) in. One will end up on this new page when clicking the event in the upcoming events section of a child's profile page.
The new page contains the same kind of Ticketmaster password showing functionality as exists already on a different page, so the password thing was refactored into its own separate component.

KK-899 | Add enrolled Ticketmaster event page

---

src/domain/api/generatedTypes/eventQuery.ts
src/domain/api/generatedTypes/eventTicketmasterPasswordQuery.ts
src/domain/api/generatedTypes/ticketmasterEventQuery.ts
src/domain/event/EventRedirect.tsx
src/domain/event/TicketmasterEventIsEnrolled.tsx
src/domain/event/queries/eventQuery.ts
src/domain/event/queries/ticketmasterEventQuery.ts

Changed external ticket system (=Ticketmaster ATM) links to use the URL field related to an event instead of the one related to an occurrence.
[KK-962](https://helsinkisolutionoffice.atlassian.net/browse/KK-962)

KK-962 | Use event related external ticket system URL

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/event/Event.tsx
src/domain/event/event.module.scss

Removed the whole enrollment part containing the occurrences list and some filters for those from the unenrolled event view when the event is Ticketmaster based, because Ticketmaster events won't be having any occurrences. Instead a button which leads to the Ticketmaster enrollment process is shown.
[KK-959](https://helsinkisolutionoffice.atlassian.net/browse/KK-959)

Remove occurrences from unenrolled Ticketmaster event page

---

src/domain/child/ChildEnrolmentCount.tsx

For now we want to disable the enrolment limit with the easiest solution possible, so the limit will be set to an unreachable number, and this PR hides that number from showing.
[KK-965](https://helsinkisolutionoffice.atlassian.net/browse/KK-965)

KK-965 | Hide enrolment limit

---

CHANGELOG.md
package.json
src/common/route/utils/replaceLocaleInPathname.ts
src/domain/app/layout/utilityComponents/PageMeta.tsx

KK-995.
The locale was replaced from anywhere from the URL pathname,
when it should have been replaced only from the beginning.
This led to a situation where e.g `/enrol` part of the pathname
was replaced with `rol`.

Fix the URL locale handling

---

src/common/translation/i18n/fi.json
src/domain/home/moreInfo/MoreInfoLinkList.tsx
src/domain/home/moreInfo/__tests__/__snapshots__/MoreInfoLinkList.test.tsx.snap
src/domain/home/moreInfo/moreInfoLinkList.module.scss

also:
- remove title from link in MoreInfoLinkList
- stylize the localized language name in parentheses to be less
prominent as the native language name
- update test snapshots
Example:
- Finnish: "Français (ranska)"
- Swedish: "Français (Franska)"
- English: "Français (French)"
refs KK-1000
[KK-1000](https://helsinkisolutionoffice.atlassian.net/browse/KK-1000)
[KK-1000]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1000 | feat: show localized language name in parentheses in MoreInfoLinkList

---

src/domain/app/state/ui/UIReducers.ts
src/domain/auth/state/BackendAuthenticationReducer.ts
src/domain/event/state/EnrolledReducers.tsx
src/domain/event/state/EventReducers.tsx
src/domain/profile/state/ProfileReducers.tsx
src/domain/registration/state/RegistrationReducers.tsx

KK-1017. Usage with the "Builder Callback" Notation, since the old  "map object" notation is now deprecated.

refactor: migrate reducers since the creation method is deprecated

---

src/common/components/formikWrappers/FormikDropdown.tsx

KK-1044.
Critical fix to Select-components that did not work
in mobile view mode without crashing browser.

fix: formik dropdown component in mobile view mode

---

src/domain/home/__tests__/__snapshots__/Home.test.jsx.snap
src/domain/home/moreInfo/MoreInfoLinkList.tsx
src/domain/home/moreInfo/__tests__/__snapshots__/HomeMoreInfo.test.tsx.snap
src/domain/home/moreInfo/__tests__/__snapshots__/MoreInfoLinkList.test.tsx.snap
src/domain/home/moreInfo/constants/MoreInfoConstants.tsx

KK-1060.
The URLs were broken, because they had a needless parameter there (after the huge dependency upgrade that was done recently).

fix: front page info links to brochure PDFs

---

src/domain/home/hero/hero.module.scss

NOTE:
- Zooming may make the background color position change a tiny bit which shows up as a discrepancy between the change from the yellow color and the grey color, like a one pixel offset or sometimes not
The background color was more white, now it is var(--color-black-5)
which is #f2f2f2 which is almost the same as #f1f1f1 which would be
the value from the hero image's lower part. Chose to use --color-black-5
because it was provided by HDS and was almost the same color.
refs KK-738
[KK-738](https://helsinkisolutionoffice.atlassian.net/browse/KK-738)
[KK-738]: https://helsinkisolutionoffice.atlassian.net/browse/KK-738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-738 | fix: set correct background color behind hero image's lower grey part

---

src/domain/home/__tests__/__snapshots__/Home.test.jsx.snap
src/domain/home/partners/__tests__/__snapshots__/HomePartners.test.tsx.snap
src/domain/home/partners/__tests__/__snapshots__/PartnersLogoList.test.tsx.snap
src/domain/home/partners/constants/PartnersConstants.tsx

refs KK-1034
[KK-1034](https://helsinkisolutionoffice.atlassian.net/browse/KK-1034)
[KK-1034]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1034 | fix: use https instead of http in partner links, fix security warning

---

src/domain/api/generatedTypes/graphql.tsx
src/domain/child/mutation/ChildMutation.ts
src/domain/child/queries/ChildQueries.ts
src/domain/child/types/ChildByIdQueryTypes.ts
src/domain/child/types/DeleteChildMutationTypes.ts
src/domain/child/types/UpdateChildMutationTypes.ts
src/domain/event/__tests__/EventPage.test.tsx
src/domain/event/enrol/Enrol.tsx
src/domain/event/mutations/enrolOccurrenceMutation.ts
src/domain/event/mutations/unenrolOccurrenceMutation.ts
src/domain/event/partial/OccurrenceInfo.tsx
src/domain/event/queries/eventQuery.ts
src/domain/event/queries/externalTicketSystemEventQuery.ts
src/domain/event/queries/occurrenceQuery.ts
src/domain/event/types/EnrolOccurrenceMutationTypes.ts
src/domain/event/types/EventChildTypes.ts
src/domain/event/types/EventQueryTypes.ts
src/domain/event/types/ExternalTicketSystemEventQueryTypes.ts
src/domain/event/types/OccurrenceQueryTypes.ts
src/domain/event/types/UnenrolOccurrenceMutationTypes.ts
src/domain/eventGroup/queries/eventGroupQuery.ts
src/domain/eventGroup/types/EventGroupQueryTypes.ts
src/domain/languages/queries/LanguageQueries.ts
src/domain/languages/types/LanguageQueryTypes.ts
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/profile/queries/ProfileQuery.ts
src/domain/profile/types/ProfileQueryTypes.ts
src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
src/domain/registration/types/SubmitChildrenAndGuardianMutationTypes.ts

Rationale here is to reduce manual maintenance of types and thus make
their maintenance easier.
Didn't find an easy way to generate the exact types for the union types,
e.g. InternalOrTicketSystemEnrolment, so those have to be maintained
manually. There were some union types generated automatically, e.g.
InternalOrTicketSystemEnrolmentUnion, but it seems they are not exactly
the types that are needed.
refs KK-1065
[KK-1065](https://helsinkisolutionoffice.atlassian.net/browse/KK-1065)
[KK-1065]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1065 | refactor: generate most subtypes with graphql-codegen using fragments

---

src/domain/languages/LanguagesCombobox.tsx

For some reason loading spinner on language load causes the initial focus on the combobox. Also tested with default hds combobox, then if there are 2 combo field, always the last one gets focus. Removed loading spinner and now it works.

fix: languages focus on load removed

---

src/domain/child/ChildEventInvitationLabel.tsx
src/domain/child/useChildEnrolmentCount.ts
src/domain/headlessCms/HeadlessCmsPage.tsx

Fixing the invite link visibility logic and double notification on hcrc page
[KK-925](https://helsinkisolutionoffice.atlassian.net/browse/KK-925)
[KK-1067](https://helsinkisolutionoffice.atlassian.net/browse/KK-1067)
[KK-925]: https://helsinkisolutionoffice.atlassian.net/browse/KK-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KK-1067]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: invite link and notification

---

src/common/route/utils/__tests__/getPathname.test.ts
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/api/generatedTypes/graphql.tsx
src/domain/app/layout/SimpleFormPageLayout.tsx
src/domain/app/layout/utilityComponents/SimpleFormTemplate.tsx
src/domain/app/layout/utilityComponents/simpleFormTemplate.module.scss
src/domain/app/routes/browserRouter.tsx
src/domain/home/form/__test__/HomePreliminaryFormUtils.test.ts
src/domain/profile/modal/EditMyProfileForm.tsx
src/domain/profile/modal/__tests__/EditProfileModal.test.tsx
src/domain/profile/mutations/updateMyMarketingSubscriptionsMutation.ts
src/domain/profile/mutations/updateMyProfileMutation.ts
src/domain/profile/queries/MyMarketingSubscriptionsQuery.ts
src/domain/profile/queries/ProfileQuery.ts
src/domain/profile/state/ProfileReducers.tsx
src/domain/profile/subscriptions/ManageSubscriptions.tsx
src/domain/profile/subscriptions/ManageSubscriptionsForm.tsx
src/domain/registration/form/RegistrationForm.tsx
src/domain/registration/mutations/submitChildrenAndGuardianMutation.ts
src/domain/registration/notEligible/__tests__/NotEligibleUtils.test.ts
src/domain/registration/state/RegistrationReducers.tsx
src/domain/registration/types/RegistrationTypes.ts

KK-1072 KK-1099.
1. Add "has accepted marketing" -field to the edit my profile form.
2. Add the "has accepted marketing checkbox to registration form. The "accept marketing" input should be available already in when making the
registration.
3. Add a manage subscriptions route to manage marketing subscriptions.
Created a new simple form template and page layout for very simple forms and used it with the ManageSubscriptions route.
The ManageSubscriptions uses the ManageSubscriptionsForm that currently holds only 1 checkbox field to enable or disable the marketing letter notifications. If it is checked, the "has accepted marketing" field will be set to true and a `UpdateMyMarketingSubscriptionsMutation` will be sent to the API.
The page can only be viewed as authenticated or if a valid …

Manage marketing subscriptions

---

src/domain/profile/Profile.tsx
src/domain/profile/ProfileProvider.tsx

KK-1146 KK-1097
Test:
1. Login to the Kukkuu UI with an account that has not registerated yet.
2. When forwarded to the Profile page, the profile page should redirect the user to home page registration form, because there is no suer registrated.

fix: profile page redirects to home when no registrated user

---

src/domain/home/form/HomePreliminaryForm.tsx

KK-1035.
The redirect url is wrong when registration is clicked before authentication. The redirect_url should always be the same (/callback), but the url-state can be set to tell where to redirect after the successfull login.

fix: registration before authentication flow

---

src/domain/app/routes/useLocaleRouteNavigate.tsx

KK-1153.
Because the useLocaleRouteNavigate did not include location hash in the redirect URL, the register-hash of the front page was not included in login-commands or the unauthorized in profile-page redirections.

fix: locale route navigate should use the location hash

---

src/domain/profile/ProfileProvider.tsx
src/domain/profile/children/ProfileChildrenList.tsx
src/domain/profile/children/child/ProfileChildDetail.tsx
src/domain/profile/hooks/useProfile.ts
src/domain/registration/form/RegistrationForm.tsx

KK-1151
The children listing on profile page should update when a new child is added or when 1 is removed or updated. The refetchProfile did not use the new refreshed data, but the old data instead.

fix: children list should update from CRUD-operations

---

package.json
src/domain/app/__tests__/__snapshots__/Layout.test.tsx.snap
src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/domain/profile/ProfileProvider.tsx
src/domain/profile/hooks/useProfileFetcher.ts
yarn.lock

KK-1152.
Fix token renewal reloaded page when user had no profile.
Upgrade to the lates tHDS-react with the latest HDS-core. This version had some fixes related to the HDS login provider.

Fix token renewal reloaded page when user had no profile

---

src/domain/registration/form/RegistrationForm.tsx
src/domain/registration/form/__tests__/RegistrationForm.test.tsx

refs KK-1178
[KK-1178](https://helsinkisolutionoffice.atlassian.net/browse/KK-1178)
[KK-1178]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1178 | feat: make RegistrationForm's hasAcceptedCommunication checkbox opt-out

---

src/common/components/alert/AlertModal.tsx
src/common/components/confirm/ConfirmModal.tsx
src/common/components/mandatoryFieldLegend/MandatoryFieldLegend.tsx
src/common/components/mandatoryFieldLegend/mandatoryFieldLegend.module.scss
src/common/components/modal/Modal.tsx
src/common/components/modal/__tests__/Modal.test.tsx
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/registration/form/RegistrationForm.tsx
src/domain/registration/form/partial/childFormFields.tsx
src/domain/registration/form/registrationForm.module.scss

refs KK-1190
[KK-1190](https://helsinkisolutionoffice.atlassian.net/browse/KK-1190)
[KK-1190]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1190 | feat: add required * and explanation text to Modal & RegistrationForm

---

src/domain/child/form/ChildForm.tsx

refs KK-1190 (noticed during this ticket)
[KK-1190](https://helsinkisolutionoffice.atlassian.net/browse/KK-1190)
[KK-1190]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make child name optional in child form

---

src/domain/registration/notEligible/NotEligible.tsx
src/domain/registration/notEligible/__tests__/__snapshots__/NotEligible.test.tsx.snap

KK-1204
The button appended the full link to the current pathname. To fix this,
the navigate-command is changed to an actual link that wraps the button.
The new page will be opened in a new blank tab.

fix: not eligible component external link

---

.env.development
.env.test
README.md
azure-pipelines-review.yml
src/domain/headlessCms/__tests__/client.test.ts

done:
- replace string "https://kukkuu.hkih.stage.geniem.io/" with string
"https://kukkuu.app-staging.hkih.hion.dev/"
refs KK-1196
[KK-1196](https://helsinkisolutionoffice.atlassian.net/browse/KK-1196)
[DevOps PR #8982](https://dev.azure.com/City-of-Helsinki/kukkuu/_git/kukkuu-pipelines/pullrequest/8982)
[KK-1196]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1196 | Use new staging CMS url https://kukkuu.app-staging.hkih.hion.dev/

---

src/common/translation/i18n/fi.json
src/domain/home/__tests__/__snapshots__/Home.test.jsx.snap
src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
src/domain/home/moreInfo/__tests__/__snapshots__/HomeMoreInfo.test.tsx.snap

refs KK-1223
[KK-1223](https://helsinkisolutionoffice.atlassian.net/browse/KK-1223)
[KK-1223]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1223 | fix: "Kultuurin" typo with "Kulttuurin"

---

package.json
yarn.lock

KK-1248.
Fixes the issue when a user navigated from the event page to the event redirect page while enrolling to an event of an external ticket system.
----
Related: https://github.com/apollographql/apollo-client/issues/11639
The issue was:
> Console has a following error “Uncaught TypeError: Cannot convert object to primitive value“, but it does not tell where it happens.
Steps to reproduce:
Click “Jatka ilmoittautumaan“
Result: The loading spinner spins forever and an error is written in the console.

fix: upgrade apollo client to fix navigation issues

---

src/domain/home/__tests__/__snapshots__/Home.test.tsx.snap
src/domain/home/moreInfo/__tests__/__snapshots__/HomeMoreInfo.test.tsx.snap
src/domain/home/moreInfo/__tests__/__snapshots__/MoreInfoLinkList.test.tsx.snap
src/domain/home/moreInfo/constants/MoreInfoConstants.tsx

Set language names for Ukrainian and Sami languages to texts given by the product owner.
[KK-588](https://helsinkisolutionoffice.atlassian.net/browse/KK-588) (Sami)
[KK-1237](https://helsinkisolutionoffice.atlassian.net/browse/KK-1237) (Ukrainian)
[KK-588]: https://helsinkisolutionoffice.atlassian.net/browse/KK-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KK-1237]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1237 | Fix language names Українська → Українська мова and Davvisámi → Davvisámegiella

---

README.md
browser-tests/childrenFeature.ts
browser-tests/constants.ts
browser-tests/utils/register.ts

Fix browser tests by using existing project year 2020 as child's birthyear
[KK-1375](https://helsinkisolutionoffice.atlassian.net/browse/KK-1375)
[KK-1375]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1375 | Fix browser tests by using existing project year 2020 as child's birthyear

---

src/domain/app/__tests__/Layout.test.tsx
src/domain/app/__tests__/__mocks__/pageQueryResponse.ts
src/domain/app/navigation/Navigation.tsx
src/domain/app/navigation/__mocks__/headerMenuMock.ts
src/domain/app/notification/__mocks__/notificationMock.ts
src/domain/app/notification/notificationQuery.ts
src/domain/auth/Unauthorized.tsx
src/domain/event/__tests__/EventIsEnrolled.test.tsx
src/domain/event/__tests__/EventOccurrence.test.tsx
src/domain/event/__tests__/EventOccurrenceList.test.tsx
src/domain/event/__tests__/__snapshots__/EventOccurrenceList.test.tsx.snap
src/domain/event/enrol/__tests__/Enrol.test.tsx
src/domain/profile/__tests__/Profile.test.tsx
src/domain/profile/events/__tests__/ProfileEvents.test.tsx
src/domain/profile/events/__tests__/ProfileEventsList.test.tsx
src/domain/profile/modal/__tests__/EditProfileModal.test.tsx
src/domain/registration/form/RegistrationForm.tsx
src/domain/registration/form/__tests__/RegistrationForm.test.tsx
src/domain/registration/form/__tests__/__snapshots__/RegistrationForm.test.tsx.snap
src/domain/registration/form/registrationForm.module.scss
tests/vitest-setup.ts

Handle most warnings from running tests.
Two deprecation warning categories from react are not fixed:
- From react because of hds-react package's use:
- Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
- From CSSTransition component in react-transition-group package related to toast animation:
- findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
- https://18.react.dev/reference/react-dom/findDOMNode
<details>
<summary>Test warnings before this PR (Click to expand)</summary>
```
$ yarn test
yarn run v1.22.22
$ cross-env …
```

KK-1372 | Handle most warnings from running tests

---

src/domain/app/layout/listPageLayout.module.scss
src/domain/app/layout/utilityComponents/infoTemplate.module.scss
src/domain/app/layout/utilityComponents/simpleFormTemplate.module.scss
src/domain/app/notFound/notFound.module.scss
src/domain/event/event.module.scss
src/domain/home/form/homePreliminaryForm.module.scss
src/domain/home/hero/hero.module.scss
src/domain/home/partners/partnerLogoList.module.scss
src/domain/profile/modal/editProfileModal.module.scss
src/domain/registration/form/partial/childFormFields.module.scss
src/domain/registration/form/registrationForm.module.scss
src/domain/registration/notEligible/notEligible.module.scss

fix all of the following warnings when building (i.e. "yarn build"):
```
Deprecation Warning: Sass's behavior for declarations that appear after
nested rules will be changing to match the behavior specified by CSS in
an upcoming version. To keep the existing behavior, move the declaration
above the nested rule. To opt into the new behavior, wrap the
declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
```
by moving CSS parts around, I checked that there were no dependencies
between the moved CSS parts that would make the end result functionally
different if they were moved.
refs KK-1372
[KK-1372](https://helsinkisolutionoffice.atlassian.net/browse/KK-1372)
[KK-1372]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

KK-1372 | Fix Sass nested rule deprecation warnings

---

Dockerfile

Enable polling only for Docker development as an alternative to PR #624.
[KK-1367](https://helsinkisolutionoffice.atlassian.net/browse/KK-1367)
Ran "docker compose up --build", opened UI in web browser, changed HomeHero.tsx's description text a few times, and avot it changed into the web browser with some delay.
[KK-1367]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1367 | Use polling in docker development to enable hot reload

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/commit-msg
.husky/pre-commit
.lintstagedrc.json
CHANGELOG.md
CONTRIBUTING.md
README.md
commitlint.config.cjs
package.json
public/hds-favicon-kit/README.md
src/assets/styles/layout.scss
src/domain/app/footer/footer.module.scss
src/domain/auth/README.md
src/domain/home/hero/hero.module.scss
src/domain/home/partners/partnerLogoList.module.scss
src/domain/registration/form/registrationForm.module.scss
yarn.lock

KK-1347.
The Git commits should be linted and the code changes should be tested before the commit is committed.
- Installed Husky as a pre commit tool.
- Installed commitlint as a tool to check the conventional commit format.
- Installed lint-staged as a tool to gather the staged git files.
Used this as a guide:
https://theodorusclarence.com/shorts/husky-commitlint-prettier.

chore: install and init husky and commitlint

---

package.json
yarn.lock

resolve cookie & @types/cookie for <v1 versions to latest v0.*,
fix dependabot issue #140:
https://github.com/City-of-Helsinki/kukkuu-ui/security/dependabot/140
"cookie accepts cookie name, path, and domain with out of bounds
characters"
> Dependabot cannot update cookie to a non-vulnerable version
> The latest possible version that can be installed is 0.4.2 because of
> the following conflicting dependencies:
>
> hds-react@3.11.0 requires cookie@^0.4.1
> msw@2.7.0 requires cookie@^0.7.2 via @bundled-es-modules/cookie@2.0.1
> react-router@7.1.1 requires cookie@^1.0.1
> react-router-dom@7.1.1 requires cookie@^1.0.1 via a transitive
> dependency on react-router@7.1.1
> The earliest fixed version is 0.7.0.
refs KK-1356
- [KK-1356](https://helsinkisolutionoffice.atlassian.net/browse/KK-1356) …

KK-1356 | Fix dependabot issue #140 i.e. cookie <0.7.0 security vulnerability

---

package.json
src/common/localization/setLocale.tsx
src/common/time/TimeConstants.ts
src/common/time/utils.tsx
src/domain/event/Event.tsx
src/domain/event/EventNotificationSubscriptionModal.tsx
src/domain/event/EventOccurrence.tsx
src/domain/event/EventUtils.tsx
src/domain/event/partial/OccurrenceInfo.tsx
src/domain/profile/children/child/ProfileChild.tsx
src/domain/profile/children/child/ProfileChildEnrolment.tsx
yarn.lock

KK-1253.
With minimum effort, replace the old unsupported momentjs library usage
with date-fns implementations.

refactor(time-utils): replace moment with date-fns

---

src/domain/app/AppConfig.ts

Probable hypothesis at the moment is that in the CI/CD pipeline `VITE_OIDC_SESSION_POLLING_INTERVAL_MS` environment variable got the value "" i.e. an empty string, and that got handled like a zero i.e. it tried to poll repeatedly, and made the browser tests pop up a window saying your session has expired.
Now `VITE_OIDC_SESSION_POLLING_INTERVAL_MS` and
`VITE_IDLE_TIMEOUT_IN_MS` neither use empty string as a value, but use their fallback values if given one.
refs KK-1411
[KK-1411](https://helsinkisolutionoffice.atlassian.net/browse/KK-1411)
[KK-1411]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1411 | Fix browser tests in CI/CD pipeline by fixing polling interval/timeout

---

index.html

KK-1407
Added the following meta-tag for CSP:
```html
<meta
http-equiv="Content-Security-Policy"
content="
...
"
/>
```
CMS demo page available at https://kukkuu-ui-pr647.dev.hel.ninja/fi/demosivu. Also, there are lots of pages behind the authorization.

feat: add csp meta-tag

---

src/domain/app/footer/__mocks__/languagesMock.ts
src/domain/headlessCms/client.ts
src/domain/languages/constants.ts
src/domain/profile/modal/__tests__/EditProfileModal.test.tsx
src/domain/registration/form/__tests__/RegistrationForm.test.tsx

to ameliorate the current CMS query speed issues hardcode the CMS
languages query response to apollo client's cache, this is acceptable
as the CMS language query's data is practically constant
CMS languages query could even be replaced with a language enumeration
(i.e. 'fi' | 'sv' | 'en' basically) use if `react-helsinki-headless-cms`
would be updated to use such
refs KK-1406
[KK-1406](https://helsinkisolutionoffice.atlassian.net/browse/KK-1406)
[KK-1406]: https://helsinkisolutionoffice.atlassian.net/browse/KK-1406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

KK-1406 | Hardcode CMS languages for faster language rendering in header

---

package.json
src/domain/app/AppConfig.ts
src/domain/headlessCms/__tests__/client.test.ts
src/domain/headlessCms/cache.ts
src/domain/headlessCms/client.ts
src/domain/headlessCms/persistor.ts
yarn.lock

KK-1406.
Installed apollo3-cache-persist.
Refactored code by spitting the CMS client code to multiple files.
Implemented `TimedApolloCachePersistor` that creates a new persisted Apollo cache persistor with an expiration time. This class automatically clears expired caches and provides methods for persisting and restoring the cache to/from localStorage.
The language(s) queries are now hard coded to the Apollo client's in memory cache in the apollo client's initialization, so there is no need to handle cache or queries related those anymore.

feat: use apollo client local storage cache persister

---

src/hooks/useRHHCConfig.tsx

KK-1406.
NOTE: This works best together with the #662, that brings the cached menu.

feat: use react-router Link in scope of RHHC

---

package.json
src/hooks/useRHHCConfig.tsx
yarn.lock

Depends on RHHC PR #203's changes that started mapping the linkUrl in
Notification component through getRoutedInternalHref:
https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/203
These RHHC changes were published to npm as
react-helsinki-headless-cms v1.0.1.
At kukkuu-ui side the getRoutedInternalHref function was bugged because
forEach doesn't return anything else but undefined:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
> forEach() always returns undefined and is not chainable. The typical
> use case is to execute side effects at the end of a chain.
Switching from forEach to a for loop made the getRoutedInternalHref work
refs KK-1424
- [KK-1424](https://helsinkisolutionoffice.atlassian.net/browse/KK-1424)
- …

KK-1424 | Fix routing of internal hrefs in Notification

---

package.json
yarn.lock

Revert merged dependabot PRs because they caused problems in tests:
- https://github.com/City-of-Helsinki/kukkuu-ui/pull/672
- https://github.com/City-of-Helsinki/kukkuu-ui/pull/659
Dependabot should be able to create new PRs after the downgrade of the related components.

Revert merged dependabot PRs #659 & #672

---

.prod/nginx.conf.template
public/50x.html
src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/app/errorElement/ApplicationError.module.scss
src/domain/app/errorElement/ApplicationError.tsx
src/domain/app/routes/browserRouter.tsx

KK-1438.
1. When a route does not have an errorElement, errors will bubble up
through parent routes. See more: https://reactrouter.com/6.30.0/route/error-element#default-error-element
The easies way to test is to add an error to a router loader: 
```typescript
{
path: '/:locale/*',
Component: WithProfileChildRouteAuthorization(WithLocaleRoute(Layout)),
loader: async ({ params }) => {
return undefined();
},
errorElement: <ApplicationError />,
```
2. Add a custom Kukkuu themed error page to Nginx.
The easiest way to test Nginx error page is to provide a location that
throws an error:
```
server {
listen 80;
location /throw503 {
return 503;
}
}
```

Add missing error elements to Nginx and React-Router implementation

---

src/common/translation/i18n/en.json
src/common/translation/i18n/fi.json
src/common/translation/i18n/sv.json
src/domain/app/AppConfig.ts
src/domain/event/EventIsEnrolled.tsx
src/domain/event/EventUtils.tsx
src/domain/event/__tests__/EventIsEnrolled.test.tsx
src/domain/event/enrol/Enrol.tsx
src/domain/event/modal/UnenrolModal.tsx

KK-1436.
Add `AppConfig.enrolmentCancellationTimeLimitHours` that can be used to configure the time (in hours) that limits the cancellation time.

feat: unenrolment should be available only over 48h before occurrence

---

.yarnrc

Discussed with @tuomas777 and decided to default to frozen lockfile to prevent unintentional dependency upgrades. In future, to upgrade a package please refer to dependabot or yarn upgrade <package_name> command.

fix: stricter yarn configuration
